import { Project, Client, File } from '@/types';

// export const mockProjects: Project[] = [
//   {
//     id: "1",
//     name: "Website Redesign",
//     description: "Complete redesign of company website",
//     status: "in_progress",
//     priority: "high",
//     createdAt: new Date("2024-01-15"),
//   },
//   {
//     id: "2",
//     name: "Mobile App Development",
//     description: "iOS and Android app development",
//     status: "new",
//     priority: "medium",
//     createdAt: new Date("2024-02-01"),
//   },
//   {
//     id: "3",
//     name: "Database Migration",
//     description: "Migrate to new database infrastructure",
//     status: "in_review",
//     priority: "high",
//     createdAt: new Date("2024-01-20"),
//   },
//   {
//     id: "4",
//     name: "API Documentation",
//     description: "Create comprehensive API documentation",
//     status: "completed",
//     priority: "low",
//     createdAt: new Date("2024-01-10"),
//   },
//   {
//     id: "5",
//     name: "Security Audit",
//     description: "Full security audit and implementation",
//     status: "in_progress",
//     priority: "high",
//     createdAt: new Date("2024-02-05"),
//   },
// ];

// export const mockClients: Client[] = [
//   {
//     id: "1",
//     name: "Tech Solutions Inc.",
//     type: "company",
//     value: 150000,
//     from: new Date("2024-01-01"),
//     to: new Date("2024-12-31"),
//   },
//   {
//     id: "2",
//     name: "Maria Rodriguez",
//     type: "person",
//     value: 25000,
//     from: new Date("2024-02-01"),
//     to: new Date("2024-08-01"),
//   },
//   {
//     id: "3",
//     name: "Global Enterprises",
//     type: "company",
//     value: 300000,
//     from: new Date("2024-01-15"),
//     to: new Date("2025-01-15"),
//   },
//   {
//     id: "4",
//     name: "Juan Perez",
//     type: "person",
//     value: 15000,
//     from: new Date("2024-03-01"),
//     to: new Date("2024-06-01"),
//   },
//   {
//     id: "5",
//     name: "Innovation Labs",
//     type: "company",
//     value: 200000,
//     from: new Date("2024-02-01"),
//     to: new Date("2024-11-30"),
//   },
//   {
//     id: "6",
//     name: "Sofia Martinez",
//     type: "person",
//     value: 35000,
//     from: new Date("2024-01-20"),
//     to: new Date("2024-07-20"),
//   },
//   {
//     id: "7",
//     name: "Digital Dynamics",
//     type: "company",
//     value: 180000,
//     from: new Date("2024-02-15"),
//     to: new Date("2025-02-15"),
//   },
//   {
//     id: "8",
//     name: "Carlos Gomez",
//     type: "person",
//     value: 20000,
//     from: new Date("2024-03-10"),
//     to: new Date("2024-09-10"),
//   },
//   {
//     id: "9",
//     name: "Future Systems",
//     type: "company",
//     value: 250000,
//     from: new Date("2024-01-05"),
//     to: new Date("2024-12-05"),
//   },
//   {
//     id: "10",
//     name: "Ana Lopez",
//     type: "person",
//     value: 28000,
//     from: new Date("2024-02-20"),
//     to: new Date("2024-08-20"),
//   },
// ];

// export const mockFiles: File[] = [
//   {
//     id: "1",
//     name: "Project Proposal.pdf",
//     description: "Initial project proposal document",
//     type: "PDF",
//     createdAt: new Date("2024-01-10"),
//   },
//   {
//     id: "2",
//     name: "Design Mockups.fig",
//     description: "UI/UX design mockups",
//     type: "Figma",
//     createdAt: new Date("2024-01-15"),
//   },
//   {
//     id: "3",
//     name: "Contract.docx",
//     description: "Signed client contract",
//     type: "Word",
//     createdAt: new Date("2024-01-20"),
//   },
//   {
//     id: "4",
//     name: "Budget Spreadsheet.xlsx",
//     description: "Project budget breakdown",
//     type: "Excel",
//     createdAt: new Date("2024-01-25"),
//   },
//   {
//     id: "5",
//     name: "Architecture Diagram.png",
//     description: "System architecture diagram",
//     type: "Image",
//     createdAt: new Date("2024-02-01"),
//   },
// ];
